# kubectl apply -f https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v1.4.0/secrets-store-csi-driver.yaml
# kubectl apply -f https://github.com/aws/secrets-store-csi-driver-provider-aws/releases/latest/download/aws-provider-installer.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-aws-secrets
  namespace: roboshop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "roboshop/rabbitmq"   # AWS Secrets Manager secret name
        objectType: "secretsmanager"
  secretObjects: # Optional: sync to k8s secret
    - secretName: rabbitmq # Kubernetes Secret that will be created
      type: Opaque
      data:
        - objectName: "roboshop/rabbitmq"
          key: RABBITMQ_DEFAULT_USER
        - objectName: "roboshop/rabbitmq"
          key: RABBITMQ_DEFAULT_PASS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          envFrom:
            - secretRef:
                name: rabbitmq # Secret automatically synced from AWS
      volumes:
        - name: rabbitmq-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "rabbitmq-aws-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
