# kubectl apply -f https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v1.4.0/secrets-store-csi-driver.yaml
# kubectl apply -f https://github.com/aws/secrets-store-csi-driver-provider-aws/releases/latest/download/aws-provider-installer.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rabbitmq-aws-secrets
  namespace: roboshop
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "rabbitmq-password"
        objectType: "secretsmanager"
  secretObjects: # Sync AWS secret to k8s secret
    - secretName: rabbitmq
      type: Opaque
      data:
        - objectName: "roboshop/rabbitmq"
          key: RABBITMQ_DEFAULT_USER
        - objectName: "roboshop/rabbitmq"
          key: RABBITMQ_DEFAULT_PASS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      serviceAccountName: roboshop-mysql-secret-reader
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          envFrom:
            - secretRef:
                name: rabbitmq
          ports:
            - containerPort: 5672   # AMQP
            - containerPort: 15672  # Management UI
          volumeMounts:
            - name: rabbitmq-secrets
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: rabbitmq-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "rabbitmq-aws-secrets"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  selector:
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
