apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  template:
    metadata:
      labels:
        component: mysql
        project: roboshop
        tier: database
    spec:
      serviceAccountName: roboshop-mysql-secret-reader
      volumes:
        - name: mysql-secret
          emptyDir: {}
        - name: mysql-data
          emptyDir: {}
      initContainers:
        - name: fetch-secret
          image: amazon/aws-cli:jq
          command:
            - sh
            - -c
            - |
              # Fetch secret and parse JSON with jq
              aws secretsmanager get-secret-value --secret-id Mysql-password-reader --query SecretString --output text | jq -r .MYSQL_ROOT_PASSWORD > /tmp/mysql_root_password.txt
          volumeMounts:
            - mountPath: /tmp
              name: mysql-secret
      containers:
        - name: mysql
          image: sameershaikdevops/mysql:v2
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp
              name: mysql-secret
            - mountPath: /var/lib/mysql
              name: mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
